# Generated by Django 4.2.7 on 2023-11-20 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='status_user',
            field=models.CharField(choices=[('owner', 'владелец курса'), ('student', 'студент')], default='student', max_length=20, verbose_name='статус пользователя'),
        ),
    ]
