# Generated by Django 4.2.7 on 2023-11-20 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0003_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.FloatField(default=0, verbose_name='сумма платежа'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='course',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='оплаченный курс'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='lesson',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='оплаченный урок'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_date',
            field=models.DateField(blank=True, null=True, verbose_name='дата платежа'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_form',
            field=models.CharField(choices=[('cash', 'наличными'), ('remittance', 'перевод на счет')], default='cash', max_length=20, verbose_name='форма оплаты'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='student',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ФИО'),
        ),
    ]
